version: "3"
services:
  api:
    build: ./api
    restart: always
    # Need to wait for postgres to start
    command: ["./wait-for-it.sh", "db:5432", "--", "./api"]
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    environment:
      - PG_HOST=db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:80

  db:
    image: postgres
    restart: always
    # Set volume so database not lost after shutting down container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # Setup username, password, and database name
    environment:
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=gorm
      - POSTGRES_DB=gorm
    ports:
      - 5432:5432

  # Container to view db
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
